<!DOCTYPE html>
<html>
<head>
    <title>Enquiries Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .badge {
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 11px;
            color: white;
            display: inline-block;
        }
        .bg-warning { background-color: #ffc107; }
        .bg-info { background-color: #17a2b8; }
        .bg-success { background-color: #28a745; }
        .bg-danger { background-color: #dc3545; }
        .bg-secondary { background-color: #6c757d; }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Enquiries Report</h1>
        <p>Generated on: {{ now()->format('d-m-Y H:i:s') }}</p>
        <p>Total Enquiries: {{ $enquiries->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>S.No</th>
                <th>Enquiry No</th>
                <th>Enquiry Date</th>
                <th>Company Name</th>
                <th>Salesman</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($enquiries as $index => $enquiry)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $enquiry->enquiry_no ?? 'N/A' }}</td>
                <td>
                    @if($enquiry->enquiry_date)
                        {{ \Carbon\Carbon::parse($enquiry->enquiry_date)->format('d-m-Y') }}
                    @else
                        N/A
                    @endif
                </td>
                <td>{{ $enquiry->company_name ?? 'N/A' }}</td>
                <td>{{ $enquiry->salesman->name ?? 'N/A' }}</td>
                <td>
                    @php
                        $statusClass = '';
                        switch(strtolower($enquiry->status ?? '')) {
                            case 'pending':
                                $statusClass = 'bg-warning';
                                break;
                            case 'in progress':
                                $statusClass = 'bg-info';
                                break;
                            case 'completed':
                                $statusClass = 'bg-success';
                                break;
                            case 'cancelled':
                                $statusClass = 'bg-danger';
                                break;
                            default:
                                $statusClass = 'bg-secondary';
                        }
                    @endphp
                    <span class="badge {{ $statusClass }}">
                        {{ ucfirst($enquiry->status ?? 'Pending') }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Report generated by {{ auth()->user()->name ?? 'System' }}</p>
        <p>Page 1 of 1</p>
    </div>
</body>
</html>